/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "maxmin.h"
#include <math.h>
#include <pthread.h>

vetorDeFloats vetorzinho;
maxMinStructResultado resultado;

maxMinStruct algo(CLIENT *clnt1, CLIENT *clnt2)
{
	vetorDeFloats vetorzinho;
	for (int i = 0; i < 10; i++)
	{
		vetorzinho.x[i] = ((i - 10 / 2) * (i - 10 / 2));
	}
	for (int i = 0; i < 10; i++)
	{
		vetorzinho.x[i] = sqrt(vetorzinho.x[i]);
	}

	maxMinStruct *result;
	maxMinStruct *result2;
	maxMinStruct *resultFinal;
	result = calculaprimeirametade_100(&vetorzinho, clnt1);
	result2 = calculasegundametade_100(&vetorzinho, clnt2);
	printf("Retornando maxPM = %f e minPM = %f\n", result->max, result->min);
	printf("Retornando maxSM = %f e minSM = %f\n", result2->max, result2->min);
	resultFinal->max = (result->max > result2->max ? result->max : result2->max);
	resultFinal->min = (result->min > result2->min ? result2->min : result->min);
	return (*resultFinal);
}
void algo1(CLIENT *clnt1)
{

	maxMinStruct *result;
	result = calculaprimeirametade_100(&vetorzinho, clnt1);
	printf("Retornando maxPM = %f e minPM = %f\n", result->max, result->min);
	resultado.maxPm = result->max;
	resultado.minPm = result->min;
	// resultFinal->max = (result->max > result2->max ? result->max : result2->max);
	// resultFinal->min = (result->min > result2->min ? result2->min : result->min);
}

void algo2(CLIENT *clnt2)
{

	maxMinStruct *result2;
	result2 = calculasegundametade_100(&vetorzinho, clnt2);
	resultado.maxSm = result2->max;
	resultado.minSm = result2->min;
	// printf("Retornando maxPM = %f e minPM = %f\n", result->max, result->min);
	// printf("Retornando maxSM = %f e minSM = %f\n", result2->max, result2->min);
	// resultFinal->max = (result->max > result2->max ? result->max : result2->max);
	// resultFinal->min = (result->min > result2->min ? result2->min : result->min);
}

void *func(void *arg)
{
	char *argz = (char *)arg;

	CLIENT *clnt1 = clnt_create(argz, PROG, VERSAO, "udp");

	algo1(clnt1);
	printf("argv = %s\n", argz);
	pthread_exit(0);
}

void *func2(void *arg)
{
	char *argz = (char *)arg;

	CLIENT *clnt2 = clnt_create(argz, PROG, VERSAO, "udp");

	algo2(clnt2);
	printf("argz = %s\n", argz);
	pthread_exit(0);
}

int main(int argc, char *argv[])
{

	for (int i = 0; i < 10; i++)
	{
		vetorzinho.x[i] = ((i - 10 / 2) * (i - 10 / 2));
	}
	for (int i = 0; i < 10; i++)
	{
		vetorzinho.x[i] = sqrt(vetorzinho.x[i]);
	}

	if (argc < 3)
	{
		printf("usage: %s server_host1 server_host2\n", argv[0]);
		exit(1);
	}

	pthread_t thread1, thread2;
	pthread_create(&thread1, NULL, func, (void *)argv[1]);
	pthread_create(&thread2, NULL, func2, (void *)argv[2]);
	pthread_join(thread1, NULL);
	pthread_join(thread2, NULL);

	maxMinStruct *resultadoFinal;

	resultadoFinal->max = (resultado.maxPm > resultado.maxSm ? resultado.maxPm : resultado.maxSm);
	resultadoFinal->min = (resultado.minPm > resultado.minSm ? resultado.minSm : resultado.minPm);
	// resultFinal = algo(clnt1, clnt2);

	printf("Min = %f, Max = %f\n", resultadoFinal->min,resultadoFinal->max);
	return 0;
}
