/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAXMIN_H_RPCGEN
#define _MAXMIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct vetorDeFloats {
	float x[100];
};
typedef struct vetorDeFloats vetorDeFloats;

struct maxMinStruct {
	float max;
	float min;
};
typedef struct maxMinStruct maxMinStruct;

struct maxMinStructResultado {
	float maxPm;
	float minPm;
	float maxSm;
	float minSm;
};
typedef struct maxMinStructResultado maxMinStructResultado;

#define PROG 55555555
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define calculaPrimeiraMetade 50
extern  maxMinStruct * calculaprimeirametade_100(vetorDeFloats *, CLIENT *);
extern  maxMinStruct * calculaprimeirametade_100_svc(vetorDeFloats *, struct svc_req *);
#define calculaSegundaMetade 51
extern  maxMinStruct * calculasegundametade_100(vetorDeFloats *, CLIENT *);
extern  maxMinStruct * calculasegundametade_100_svc(vetorDeFloats *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define calculaPrimeiraMetade 50
extern  maxMinStruct * calculaprimeirametade_100();
extern  maxMinStruct * calculaprimeirametade_100_svc();
#define calculaSegundaMetade 51
extern  maxMinStruct * calculasegundametade_100();
extern  maxMinStruct * calculasegundametade_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vetorDeFloats (XDR *, vetorDeFloats*);
extern  bool_t xdr_maxMinStruct (XDR *, maxMinStruct*);

#else /* K&R C */
extern bool_t xdr_vetorDeFloats ();
extern bool_t xdr_maxMinStruct ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAXMIN_H_RPCGEN */
