/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "maxmin.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

maxMinStruct *
calculaprimeirametade_100(vetorDeFloats *argp, CLIENT *clnt)
{
	static maxMinStruct clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, calculaPrimeiraMetade,
		(xdrproc_t) xdr_vetorDeFloats, (caddr_t) argp,
		(xdrproc_t) xdr_maxMinStruct, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

maxMinStruct *
calculasegundametade_100(vetorDeFloats *argp, CLIENT *clnt)
{
	static maxMinStruct clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, calculaSegundaMetade,
		(xdrproc_t) xdr_vetorDeFloats, (caddr_t) argp,
		(xdrproc_t) xdr_maxMinStruct, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
