/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "maxmin.h"
#include <math.h>
#include <pthread.h>

// Declara as variaveis globais para as threads poderem usar
vetorDeFloats vetorzinho;
maxMinStructResultado resultado;

// Calcula a primeira metade do vetor
void calculaPm(CLIENT *clnt1)
{
	maxMinStruct *result;
	result = calculaprimeirametade_100(&vetorzinho, clnt1);
	resultado.maxPm = result->max;
	resultado.minPm = result->min;
}

// Calcula a segunda metade do vetor
void calculaSm(CLIENT *clnt2)
{
	maxMinStruct *result2;
	result2 = calculasegundametade_100(&vetorzinho, clnt2);
	resultado.maxSm = result2->max;
	resultado.minSm = result2->min;
}

void *func(void *arg)
{
	char *argz = (char *)arg;

	CLIENT *clnt1 = clnt_create(argz, PROG, VERSAO, "udp");

	calculaPm(clnt1);

	pthread_exit(0);
}

void *func2(void *arg)
{
	char *argz = (char *)arg;

	CLIENT *clnt2 = clnt_create(argz, PROG, VERSAO, "udp");

	calculaSm(clnt2);

	pthread_exit(0);
}

int main(int argc, char *argv[])
{
	// Preenche os valores do vetor de acordo com as regras de negócio
	for (int i = 0; i < 10; i++)
	{
		vetorzinho.x[i] = ((i - 10 / 2) * (i - 10 / 2));
	}
	for (int i = 0; i < 10; i++)
	{
		vetorzinho.x[i] = sqrt(vetorzinho.x[i]);
	}

	if (argc < 3)
	{
		printf("usage: %s server_host1 server_host2\n", argv[0]);
		exit(1);
	}

	// Cria as threads para calcular cada metade
	pthread_t thread1, thread2;
	pthread_create(&thread1, NULL, func, (void *)argv[1]);
	pthread_create(&thread2, NULL, func2, (void *)argv[2]);
	// Espera as threads terminarem corretamente
	pthread_join(thread1, NULL);
	pthread_join(thread2, NULL);

	maxMinStruct *resultadoFinal;

	// Compara os valores maximos e minimos de cada metade e seta na variavel resultadoFinal
	resultadoFinal->max = (resultado.maxPm > resultado.maxSm ? resultado.maxPm : resultado.maxSm);
	resultadoFinal->min = (resultado.minPm > resultado.minSm ? resultado.minSm : resultado.minPm);

	printf("Min = %f, Max = %f\n", resultadoFinal->min, resultadoFinal->max);
	return 0;
}
