/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "maxmin.h"

bool_t
xdr_vetorDeFloats (XDR *xdrs, vetorDeFloats *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->x, 10,
		sizeof (float), (xdrproc_t) xdr_float))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_maxMinStruct (XDR *xdrs, maxMinStruct *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->max))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->min))
		 return FALSE;
	return TRUE;
}
