/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "maxmin.h"

maxMinStruct *
calculaprimeirametade_100_svc(vetorDeFloats *argp, struct svc_req *rqstp)
{
	static maxMinStruct result;
	result.max = argp->x[0];
	result.min = argp->x[0];
	for (int i = 0; i < 5; i++)
	{
		if (argp->x[i] > result.max)
		{
			result.max = argp->x[i];
		}
		if (argp->x[i] < result.min)
		{
			result.min = argp->x[i];
		}
	}
	printf("Retornando maxPM = %f e minPM = %f\n", result.max, result.min);

	return &result;
}

maxMinStruct *
calculasegundametade_100_svc(vetorDeFloats *argp, struct svc_req *rqstp)
{
	static maxMinStruct result;
	result.max = argp->x[0];
	result.min = argp->x[0];
	for (int i = 5; i < 10; i++)
	{
		if (argp->x[i] > result.max)
		{
			result.max = argp->x[i];
		}
		if (argp->x[i] < result.min)
		{
			result.min = argp->x[i];
		}
	}
	printf("Retornando maxSM = %f e minSM = %f\n", result.max, result.min);

	return &result;
}
